import random
print("Geometry Dash Level ID Randomizer")
print("Made by XboxFace24 GMD")
print("Note: Most of the level IDs generated by this program")
print("do not exist on the Geometry Dash servers anymore.")
print("(if you put them in your game.)")
repeat = True
while repeat:
	print("Press return/enter to generate a random level ID.")
	confirm = input("Enter !quit to quit. ")
	if confirm == "!quit":
		break
	else:
		print(random.randint(128,89192660))
